name: word_memory
description: A Word Memory App.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.18.0
  cupertino_icons: ^1.0.2
  get: ^4.6.6
  flutter_bloc: ^8.1.4
  equatable: ^2.0.5
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.8
  bloc_test: ^9.1.5

flutter:
  uses-material-design: true

  assets:
    - assets/data/